# Generated by Django 6.0.6 on 2026-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('sinpe', 'SINPE')], max_length=30),
        ),
    ]
