# Generated by Django 6.0.6 on 2026-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='otp_current_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
