# Generated by Django 6.0.6 on 2026-06-25 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('reprint_ticket', 'Reprint ticket'), ('edit_ticket', 'Edit ticket'), ('apply_discount', 'Apply discount'), ('cancel_ticket', 'Cancel ticket'), ('close_without_code', 'Close without code')], max_length=80)),
                ('reason', models.TextField()),
                ('was_valid', models.BooleanField(default=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_otp_usages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otp_usages', to='tickets.ticket')),
                ('used_by_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_otp_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('create_wash_ticket', 'Create wash ticket'), ('create_parking_ticket', 'Create parking ticket'), ('charge_wash_ticket', 'Charge wash ticket'), ('charge_parking_ticket', 'Charge parking ticket'), ('edit_customer_data', 'Edit customer data'), ('edit_ticket', 'Edit ticket'), ('apply_discount', 'Apply discount'), ('cancel_ticket', 'Cancel ticket'), ('reprint_ticket', 'Reprint ticket'), ('close_without_code', 'Close without code'), ('reopen_ticket', 'Reopen ticket'), ('change_service_price', 'Change service price'), ('change_extra_price', 'Change extra price'), ('create_employee', 'Create employee'), ('deactivate_employee', 'Deactivate employee')], max_length=80)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='tickets.ticket')),
                ('otp_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='audit.otpusage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
