# Generated by Django 6.0.6 on 2026-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('create_wash_ticket', 'Crear ticket de lavado'), ('create_parking_ticket', 'Crear ticket de parqueo'), ('charge_wash_ticket', 'Cobrar ticket de lavado'), ('charge_parking_ticket', 'Cobrar ticket de parqueo'), ('edit_customer_data', 'Editar datos del cliente'), ('edit_ticket', 'Editar ticket'), ('apply_discount', 'Aplicar descuento'), ('cancel_ticket', 'Anular ticket'), ('reprint_ticket', 'Reimprimir ticket'), ('close_without_code', 'Cerrar sin código'), ('reopen_ticket', 'Reabrir ticket'), ('change_service_price', 'Cambiar precio de servicio'), ('change_extra_price', 'Cambiar precio de extra'), ('create_employee', 'Crear empleado'), ('deactivate_employee', 'Desactivar empleado')], max_length=80),
        ),
    ]
