# Generated by Django 6.0.6 on 2026-06-25 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=30, unique=True)),
                ('ticket_type', models.CharField(choices=[('wash', 'Wash'), ('parking', 'Parking')], max_length=30)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('active', 'Active'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=30)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=30)),
                ('vehicle_plate', models.CharField(max_length=30)),
                ('service_name_snapshot', models.CharField(max_length=120)),
                ('service_price_with_tax_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_without_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.13, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_code_hash', models.TextField()),
                ('parking_entry_at', models.DateTimeField(blank=True, null=True)),
                ('parking_exit_at', models.DateTimeField(blank=True, null=True)),
                ('parking_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_first_hour_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parking_block_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parking_block_minutes_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cash_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='cash.cashday')),
                ('created_by_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.service')),
                ('updated_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name_snapshot', models.CharField(max_length=120)),
                ('extra_price_with_tax_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate_snapshot', models.DecimalField(decimal_places=4, default=0.13, max_digits=5)),
                ('subtotal_without_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_with_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_extras', to='catalog.extra')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_extras', to='tickets.ticket')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
