# Generated by Django 6.0.6 on 2026-06-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_last_printed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closing_code_for_print',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
