# Generated by Django 6.0.6 on 2026-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_closing_code_for_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('active', 'Activo'), ('paid', 'Pagado'), ('cancelled', 'Anulado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('wash', 'Lavado'), ('parking', 'Parqueo')], max_length=30),
        ),
    ]
