# Generated by Django 6.0.6 on 2026-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_status_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parking_mode',
            field=models.CharField(choices=[('hourly', 'Por horas'), ('prepaid', 'Prepago')], default='hourly', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prepaid_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prepaid_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prepaid_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
