# Generated by Django 6.0.6 on 2026-07-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_parking_mode_ticket_prepaid_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='prepaid_plan_duration_quantity_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prepaid_plan_duration_unit_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prepaid_plan_name_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prepaid_plan_price_with_tax_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
